// Dokument WebView z mapą: wektorowe kafelki OSM w ciemnym stylu M3 (patrz
// `src/map/mapStyle.ts`), trasa, przystanki, start/cel i pojazd na żywo.
//
// Mapa żyje w WebView, bo tylko stąd da się naszpikować ją arkuszem stylów
// w palecie aplikacji: natywne mapy (Google/Apple) mają obcy wygląd i na iOS
// w ogóle nie przyjmują kafelków OSM.
//
// Komunikacja z aplikacją: RN → JS przez postMessage (MapInMessage),
// JS → RN przez window.ReactNativeWebView.postMessage (MapOutMessage).

import { scheme } from '../theme/tokens';
import { MAP_ATTRIBUTION } from '../config';
import { buildMapStyle, MAP_COLORS, ROUTE_SOURCE_ID } from './mapStyle';
import type { MapInMessage, MapOutMessage, MapRoute, MapVehicle } from './types';

const MAPLIBRE_VERSION = '4.7.1';
const MAPLIBRE_CDNS = [
  'https://cdn.jsdelivr.net/npm/maplibre-gl@' + MAPLIBRE_VERSION + '/dist',
  'https://unpkg.com/maplibre-gl@' + MAPLIBRE_VERSION + '/dist',
];

export interface RouteMapDocumentOptions {
  route: MapRoute | null;
  vehicle?: MapVehicle | null;
  follow?: boolean;
  user?: { lat: number; lon: number; heading: number | null } | null;
  selectedLegId?: string | null;
}

const theme = {
  surface: scheme.surface,
  surfaceContainerHigh: scheme.surfaceContainerHigh,
  surfaceContainerHighest: scheme.surfaceContainerHighest,
  onSurface: scheme.onSurface,
  onSurfaceVariant: scheme.onSurfaceVariant,
  outline: scheme.outline,
  outlineVariant: scheme.outlineVariant,
  primary: scheme.primary,
  onPrimary: scheme.onPrimary,
  primaryContainer: scheme.primaryContainer,
  onPrimaryContainer: scheme.onPrimaryContainer,
  tertiary: scheme.tertiary,
  success: scheme.success,
  warning: scheme.warning,
  error: scheme.error,
};

const css = [
  ':root{',
  '--k-surface:' + theme.surface + ';',
  '--k-surface-high:' + theme.surfaceContainerHigh + ';',
  '--k-surface-highest:' + theme.surfaceContainerHighest + ';',
  '--k-on-surface:' + theme.onSurface + ';',
  '--k-on-surface-var:' + theme.onSurfaceVariant + ';',
  '--k-outline:' + theme.outline + ';',
  '--k-outline-var:' + theme.outlineVariant + ';',
  '--k-primary:' + theme.primary + ';',
  '--k-on-primary:' + theme.onPrimary + ';',
  '--k-primary-container:' + theme.primaryContainer + ';',
  '--k-on-primary-container:' + theme.onPrimaryContainer + ';',
  '--k-tertiary:' + theme.tertiary + ';',
  '--k-success:' + theme.success + ';',
  '--k-warning:' + theme.warning + ';',
  '--k-error:' + theme.error + ';',
  '--k-land:' + MAP_COLORS.land + ';',
  '}',
  '*{box-sizing:border-box;-webkit-tap-highlight-color:transparent;}',
  'html,body{margin:0;padding:0;height:100%;width:100%;}',
  'body{background:var(--k-surface);color:var(--k-on-surface);overflow:hidden;overscroll-behavior:none;',
  'font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",sans-serif;}',
  '#map{position:absolute;inset:0;background:var(--k-land);touch-action:none;}',
  '.maplibregl-canvas{outline:none;}',
  '.maplibregl-canvas-container{cursor:grab;}',
  '.maplibregl-ctrl-bottom-right{pointer-events:none;}',
  '.maplibregl-ctrl-bottom-right .maplibregl-ctrl{pointer-events:auto;}',
  // ── atrybucja: mikroskopijna, w motywie aplikacji
  '.maplibregl-ctrl-attrib{margin:0 10px 6px 0 !important;padding:3px 8px !important;',
  'border-radius:10px !important;background:rgba(17,20,20,.72) !important;',
  'backdrop-filter:blur(8px);-webkit-backdrop-filter:blur(8px);',
  'box-shadow:0 1px 4px rgba(0,0,0,.35) !important;font:9px/1.4 -apple-system,sans-serif !important;',
  'color:var(--k-on-surface-var) !important;}',
  '.maplibregl-ctrl-attrib a{color:var(--k-on-surface-var) !important;text-decoration:none;}',
  '.maplibregl-ctrl-attrib-button{display:none !important;}',
  // ── popup przystanku
  '.maplibregl-popup-content{background:var(--k-surface-high) !important;color:var(--k-on-surface) !important;',
  'border:1px solid var(--k-outline-var);border-radius:16px !important;box-shadow:0 6px 22px rgba(0,0,0,.5) !important;',
  'padding:0 !important;min-width:150px;max-width:230px !important;}',
  '.maplibregl-popup-content-wrapper{background:transparent !important;padding:0 !important;}',
  '.maplibregl-popup-tip{border-top-color:var(--k-surface-high) !important;border-bottom-color:var(--k-surface-high) !important;',
  'box-shadow:none !important;}',
  '.maplibregl-popup-close-button{width:26px !important;height:26px !important;right:2px !important;top:2px !important;',
  'border-radius:999px !important;font-size:19px !important;line-height:24px !important;',
  'color:var(--k-on-surface-var) !important;background:transparent !important;padding:0 !important;}',
  '.k-pop-role{display:inline-flex;align-items:center;gap:6px;padding:8px 12px 0 12px;',
  'font-size:10px;font-weight:700;letter-spacing:.6px;text-transform:uppercase;color:var(--k-on-surface-var);}',
  '.k-pop-role i{width:8px;height:8px;border-radius:4px;display:inline-block;}',
  '.k-pop-name{font-size:14px;font-weight:700;padding:2px 12px 0 12px;line-height:1.25;word-break:break-word;}',
  '.k-pop-row{display:flex;gap:10px;align-items:baseline;padding:8px 12px 11px 12px;',
  'font-size:12px;color:var(--k-on-surface-var);}',
  '.k-pop-row b{font-size:13px;color:var(--k-on-surface);font-variant-numeric:tabular-nums;}',
  // ── pinezki startu i celu
  '.k-pin{position:relative;width:22px;height:22px;}',
  '.k-pin i{position:absolute;inset:0;border-radius:50% 50% 50% 4px;transform:rotate(-45deg);',
  'border:2px solid var(--k-land);box-shadow:0 2px 6px rgba(0,0,0,.55);}',
  '.k-pin b{position:absolute;left:50%;top:50%;width:7px;height:7px;margin:-3.5px 0 0 -3.5px;',
  'border-radius:4px;background:var(--k-land);}',
  '.k-pin-label{position:absolute;left:20px;top:-11px;white-space:nowrap;',
  'font-size:11px;font-weight:700;padding:3px 8px;border-radius:999px;',
  'background:var(--k-surface-high);color:var(--k-on-surface);',
  'border:1px solid var(--k-outline-var);box-shadow:0 2px 8px rgba(0,0,0,.45);}',
  '.k-pin-label.end{left:auto;right:20px;}',
  // ── przystanki wsiadania/wysiadania
  '.k-marker-stop{cursor:pointer;}',
  '.k-stop{position:relative;width:14px;height:14px;}',
  '.k-stop i{position:absolute;inset:3px;border-radius:50%;background:var(--k-on-surface);',
  'box-shadow:0 0 0 2px var(--k-land);}',
  '.k-stop.board i{inset:1px;background:var(--k-primary);}',
  '.k-stop.alight i{inset:1px;background:var(--k-error);}',
  '.k-stop-label{position:absolute;left:16px;top:-12px;white-space:nowrap;',
  'font-size:11px;font-weight:700;padding:3px 8px;border-radius:999px;',
  'background:var(--k-surface-high);color:var(--k-on-surface);',
  'border:1px solid var(--k-outline-var);box-shadow:0 2px 8px rgba(0,0,0,.45);}',
  '.k-stop-label.board{color:var(--k-on-primary-container);background:var(--k-primary-container);',
  'border-color:transparent;}',
  '.k-stop-label.alight{color:var(--k-error);}',
  // ── pojazd na żywo
  '.k-veh{position:relative;width:0;height:0;transition:transform 1.5s linear;}',
  '.k-veh.no-anim,.k-veh.no-anim *{transition:none !important;}',
  '.k-veh-halo{position:absolute;left:0;top:0;width:46px;height:46px;margin:-23px 0 0 -23px;',
  'border-radius:23px;background:currentColor;opacity:.22;animation:k-pulse 2.4s ease-out infinite;}',
  '@keyframes k-pulse{0%{transform:scale(.45);opacity:.32;}70%{opacity:0;}100%{opacity:0;}}',
  '.k-veh-arrow{position:absolute;left:50%;top:50%;width:0;height:0;margin:-23px 0 0 -9px;',
  'border-left:9px solid transparent;border-right:9px solid transparent;',
  'border-bottom:15px solid currentColor;transform-origin:50% 23px;',
  'filter:drop-shadow(0 1px 1px rgba(0,0,0,.85));',
  'transition:transform .5s cubic-bezier(.4,0,.2,1);}',
  '.k-veh-body{position:absolute;left:50%;top:50%;width:18px;height:18px;margin:-9px 0 0 -9px;',
  'border-radius:9px;background:currentColor;border:2.5px solid var(--k-land);',
  'box-shadow:0 0 0 1.5px rgba(255,255,255,.85),0 2px 8px rgba(0,0,0,.6);}',
  '.k-veh-label{position:absolute;left:20px;top:-14px;white-space:nowrap;display:flex;',
  'align-items:center;gap:5px;font-size:11px;font-weight:800;padding:3px 9px;border-radius:999px;',
  'background:var(--k-surface-high);color:var(--k-on-surface);',
  'border:1px solid var(--k-outline-var);box-shadow:0 2px 8px rgba(0,0,0,.45);}',
  '.k-veh-label em{font-style:normal;font-weight:700;}',
  // ── pozycja użytkownika
  '.k-user{position:relative;width:0;height:0;}',
  '.k-user-halo{position:absolute;left:0;top:0;width:34px;height:34px;margin:-17px 0 0 -17px;',
  'border-radius:17px;background:var(--k-tertiary);opacity:.18;}',
  '.k-user-dot{position:absolute;left:50%;top:50%;width:16px;height:16px;margin:-8px 0 0 -8px;',
  'border-radius:8px;background:var(--k-tertiary);border:2.5px solid var(--k-land);',
  'box-shadow:0 0 0 1.5px rgba(255,255,255,.7),0 2px 8px rgba(0,0,0,.5);}',
].join('\n');

// Runtime MapLibre + komunikacja. Świadomie bez template literalów, bo całość
// wplata się w template literal po stronie RN.
const runtime = [
  '(function () {',
  "'use strict';",
  'var P = window.__KM__ || {};',
  'var bridge = window.ReactNativeWebView;',
  'function post(msg) {',
  '  try { if (bridge && bridge.postMessage) bridge.postMessage(JSON.stringify(msg)); } catch (e) {}',
  '}',
  'function postError(message) { post({ t: "error", message: String(message) }); }',
  'function loadScript(url) {',
  '  return new Promise(function (resolve, reject) {',
  '    var s = document.createElement("script");',
  '    s.src = url; s.async = false;',
  '    s.onload = function () { resolve(url); };',
  '    s.onerror = function () { reject(new Error("skrypt " + url)); };',
  '    document.head.appendChild(s);',
  '  });',
  '}',
  'function loadCss(base) {',
  '  return new Promise(function (resolve, reject) {',
  '    var link = document.createElement("link");',
  '    link.rel = "stylesheet";',
  '    link.href = base + "/maplibre-gl.css";',
  '    link.onload = function () { resolve(base); };',
  '    link.onerror = function () { if (link.parentNode) link.parentNode.removeChild(link); reject(new Error("css " + base)); };',
  '    document.head.appendChild(link);',
  '  });',
  '}',
  'function loadMapLibre() {',
  '  var i = 0;',
  '  function attempt() {',
  '    if (i >= P.cdns.length) return Promise.reject(new Error("Nie udało się pobrać silnika mapy"));',
  '    var base = P.cdns[i++];',
  '    return loadCss(base)',
  '      .then(function () { return loadScript(base + "/maplibre-gl.js"); })',
  '      .then(function () {',
  '        if (window.maplibregl) return true;',
  '        throw new Error("maplibregl brak");',
  '      })',
  '      .catch(attempt);',
  '  }',
  '  return attempt();',
  '}',
  'var map = null;',
  'var attribution = null;',
  'var route = null;',
  'var legGeom = {};',
  'var selectedLeg = null;',
  'var following = false;',
  'var markers = [];',
  'var vehicleMarker = null;',
  'var userMarker = null;',
  'var loadFailures = 0;',
  'var tilesDown = false;',
  'var styleReady = false;',
  'var BOOTSTRAP = P.route || null;',
  '// Środek pinezki (22 px) przesunięty na koniec geograficzny punktu.',
  'var PIN_OFFSET = [-11, -21];',
  '',
  'function geom(leg) { return legGeom[leg.id] || []; }',
  '',
  'function attribNode() {',
  '  return map ? map.getContainer().querySelector(".maplibregl-ctrl-attrib") : null;',
  '}',
  '',
  'function setControlOffset(pad) {',
  '  var node = attribNode();',
  '  if (!node) return;',
  '  var bottom = pad && pad.length === 4 ? pad[2] : (P.padding ? P.padding[2] : 0);',
  '  // !important inline, bo arkusz stylów też ustawia margines atrybucji.',
  '  node.style.setProperty("margin-bottom", Math.max(0, bottom - 12) + "px", "important");',
  '}',
  '',
  'function paddingObj(pad) {',
  '  var p = pad && pad.length === 4 ? pad : P.padding;',
  '  return { top: p[0], right: p[1], bottom: p[2], left: p[3] };',
  '}',
  '',
  // ── GeoJSON: linie nóg + punkty przystanków pośrednich w jednym źródle
  'function featureCollection() {',
  '  var features = [];',
  '  if (!route) return { type: "FeatureCollection", features: features };',
  '  for (var i = 0; i < route.legs.length; i++) {',
  '    var leg = route.legs[i];',
  '    var coords = geom(leg);',
  '    if (coords.length > 1) {',
  '      features.push({',
  '        type: "Feature",',
  '        properties: {',
  '          legId: leg.id,',
  '          color: leg.color,',
  '          walk: leg.mode === "walk" ? 1 : 0,',
  '          sel: selectedLeg === leg.id ? 2 : selectedLeg ? 1 : 0,',
  '        },',
  '        geometry: { type: "LineString", coordinates: coords },',
  '      });',
  '    }',
  '    var stops = leg.stops || [];',
  '    for (var j = 0; j < stops.length; j++) {',
  '      if (stops[j].role !== "intermediate") continue;',
  '      features.push({',
  '        type: "Feature",',
  '        properties: {',
  '          stopId: stops[j].id, legId: leg.id, name: stops[j].name,',
  '          role: "intermediate", arriveSec: stops[j].arriveSec || 0,',
  '        },',
  '        geometry: { type: "Point", coordinates: [stops[j].lon, stops[j].lat] },',
  '      });',
  '    }',
  '  }',
  '  return { type: "FeatureCollection", features: features };',
  '}',
  '',
  'function clearMarkers() {',
  '  for (var i = 0; i < markers.length; i++) markers[i].remove();',
  '  markers = [];',
  '}',
  '',
  'function near(a, b) {',
  '  if (!a || !b) return false;',
  '  var dLat = (a[0] - b.lat) * 111320;',
  '  var dLon = (a[1] - b.lon) * 111320 * Math.cos((b.lat * Math.PI) / 180);',
  '  return Math.sqrt(dLat * dLat + dLon * dLon) < 22;',
  '}',
  '',
  'function routeFirstPoint() {',
  '  if (!route || !route.legs.length) return null;',
  '  var s = route.legs[0].stops || [];',
  '  return s.length ? [s[0].lon, s[0].lat] : null;',
  '}',
  '',
  'function routeLastPoint() {',
  '  if (!route || !route.legs.length) return null;',
  '  var last = route.legs[route.legs.length - 1];',
  '  var s = last.stops || [];',
  '  return s.length ? [s[s.length - 1].lon, s[s.length - 1].lat] : null;',
  '}',
  '',
  'function timeText(sec) {',
  '  if (typeof sec !== "number" || !isFinite(sec) || sec <= 0) return "";',
  '  var h = Math.floor(sec / 3600) % 24;',
  '  var m = Math.floor((sec % 3600) / 60);',
  '  return (h < 10 ? "0" : "") + h + ":" + (m < 10 ? "0" : "") + m;',
  '}',
  '',
  'function popupHtml(stop, leg) {',
  '  var role = stop.role === "board" ? "Wsiadaj" : stop.role === "alight" ? "Wysiadaj" : "Przystanek";',
  '  var color = stop.role === "board" ? "var(--k-primary)" :',
  '    stop.role === "alight" ? "var(--k-error)" : "var(--k-on-surface-var)";',
  '  var rows = "";',
  '  var t = timeText(stop.arriveSec);',
  '  if (t) rows += \'<div class="k-pop-row">\' + (stop.role === "alight" ? "Przyjazd" : "Odjazd") + "<b>" + t + "</b></div>";',
  '  if (leg.line) rows += \'<div class="k-pop-row">\' + (leg.mode === "walk" ? "Etap" : "Linia") + "<b>" + leg.line + "</b></div>";',
  '  if (leg.direction) rows += \'<div class="k-pop-row">Kierunek<b>\' + leg.direction + "</b></div>";',
  '  return \'<div class="k-pop-role"><i style="background:\' + color + \'"></i>\' + role + "</div>" +',
  '    \'<div class="k-pop-name">\' + stop.name + "</div>" + rows;',
  '}',
  '',
  'function addMarker(latlng, html, className, anchor, offset) {',
  '  var el = document.createElement("div");',
  '  el.className = className;',
  '  el.innerHTML = html;',
  '  var marker = new maplibregl.Marker({ element: el, anchor: anchor || "center", offset: offset || [0, 0] });',
  '  marker.setLngLat(latlng).addTo(map);',
  '  markers.push(marker);',
  '  return marker;',
  '}',
  '',
  'function showStopPopup(latlng, stop, leg) {',
  '  new maplibregl.Popup({ closeButton: true, closeOnClick: true, offset: 14, className: "k-popup", maxWidth: "240px" })',
  '    .setLngLat(latlng)',
  '    .setHTML(popupHtml(stop, leg))',
  '    .addTo(map);',
  '}',
  '',
  'function drawRoute() {',
  '  var src = map.getSource(P.routeSourceId);',
  '  // Przed wczytaniem stylu źródła nie ma — geometria czeka w legGeom,',
  '  // a drawRoute() wróci po zdarzeniu style.load.',
  '  if (src) src.setData(featureCollection());',
  '  clearMarkers();',
  '  if (!route) return;',
  '  var first = routeFirstPoint();',
  '  var last = routeLastPoint();',
  '  for (var i = 0; i < route.legs.length; i++) {',
  '    (function (leg) {',
  '      var stops = leg.stops || [];',
  '      for (var j = 0; j < stops.length; j++) {',
  '        (function (stop, index) {',
  '          if (stop.role !== "board" && stop.role !== "alight") return;',
  '          if (index === 0 && near(first, stop)) return;',
  '          if (index === stops.length - 1 && near(last, stop)) return;',
  '          var label = stop.role === "board" ? \'<div class="k-stop-label board">Wsiadaj</div>\' :',
  '            \'<div class="k-stop-label alight">Wysiadaj</div>\';',
  '          var marker = addMarker(',
  '            [stop.lon, stop.lat],',
  '            \'<div class="k-stop \'+ stop.role +\'"><i></i>\' + label + "</div>",',
  '            "k-marker-stop"',
  '          );',
  '          marker.getElement().addEventListener("click", function () {',
  '            post({ t: "stopTap", stopId: stop.id, legId: leg.id, name: stop.name, role: stop.role, arriveSec: stop.arriveSec });',
  '          });',
  '        })(stops[j], j);',
  '      }',
  '    })(route.legs[i]);',
  '  }',
  '  if (first) {',
  '    addMarker(first,',
  '      \'<div class="k-pin"><i style="background:var(--k-success)"></i><b></b></div>\' +',
  '        \'<div class="k-pin-label">\' + route.fromTitle + "</div>",',
  '      "k-marker-pin", "top-left", PIN_OFFSET);',
  '  }',
  '  if (last) {',
  '    addMarker(last,',
  '      \'<div class="k-pin"><i style="background:var(--k-error)"></i><b></b></div>\' +',
  '        \'<div class="k-pin-label end">\' + route.toTitle + "</div>",',
  '      "k-marker-pin", "top-left", PIN_OFFSET);',
  '  }',
  '}',
  '',
  'function legById(id) {',
  '  if (!route) return null;',
  '  for (var i = 0; i < route.legs.length; i++) if (route.legs[i].id === id) return route.legs[i];',
  '  return null;',
  '}',
  '',
  'function allCoords() {',
  '  var out = [];',
  '  if (!route) return out;',
  '  for (var i = 0; i < route.legs.length; i++) {',
  '    var c = geom(route.legs[i]);',
  '    for (var j = 0; j < c.length; j++) out.push(c[j]);',
  '  }',
  '  if (!out.length) {',
  '    for (i = 0; i < route.legs.length; i++) {',
  '      var stops = route.legs[i].stops || [];',
  '      for (j = 0; j < stops.length; j++) out.push([stops[j].lon, stops[j].lat]);',
  '    }',
  '  }',
  '  return out;',
  '}',
  '',
  'function fitAll(pad, animate) {',
  '  var pts = allCoords();',
  '  if (!pts.length) return;',
  '  if (pts.length === 1) {',
  '    map.easeTo({ center: pts[0], zoom: 15, duration: animate ? 500 : 0 });',
  '    return;',
  '  }',
  '  var b = new maplibregl.LngLatBounds();',
  '  for (var i = 0; i < pts.length; i++) b.extend(pts[i]);',
  '  map.fitBounds(b, { padding: paddingObj(pad), maxZoom: 17, duration: animate ? 500 : 0 });',
  '}',
  '',
  'function fitLeg(legId, pad, animate) {',
  '  var leg = legById(legId);',
  '  if (!leg) {',
  '    fitAll(pad, animate);',
  '    return;',
  '  }',
  '  var coords = geom(leg);',
  '  var pts = coords.length > 1 ? coords : (leg.stops || []).map(function (s) { return [s.lon, s.lat]; });',
  '  if (!pts.length) return;',
  '  if (pts.length === 1) {',
  '    map.easeTo({ center: pts[0], zoom: 16, duration: animate ? 500 : 0 });',
  '    return;',
  '  }',
  '  var b = new maplibregl.LngLatBounds();',
  '  for (var i = 0; i < pts.length; i++) b.extend(pts[i]);',
  '  map.fitBounds(b, { padding: paddingObj(pad), maxZoom: 17, duration: animate ? 500 : 0 });',
  '}',
  '',
  'function setVehicle(v) {',
  '  if (!v) {',
  '    if (vehicleMarker) { vehicleMarker.remove(); vehicleMarker = null; }',
  '    return;',
  '  }',
  '  if (!vehicleMarker) {',
  '    var el = document.createElement("div");',
  '    el.className = "k-veh";',
  '    el.style.color = v.color || "var(--k-primary)";',
  '    el.innerHTML = \'<div class="k-veh-halo"></div>\' +',
  '      \'<div class="k-veh-arrow"></div>\' +',
  '      \'<div class="k-veh-body"></div>\' +',
  '      \'<div class="k-veh-label"></div>\';',
  '    vehicleMarker = new maplibregl.Marker({ element: el });',
  '    vehicleMarker.getElement().addEventListener("click", function () {',
  '      if (following) { following = false; post({ t: "userMoved" }); }',
  '    });',
  '    vehicleMarker.setLngLat([v.lon, v.lat]).addTo(map);',
  '  } else {',
  '    vehicleMarker.setLngLat([v.lon, v.lat]);',
  '  }',
  '  var node = vehicleMarker.getElement();',
  '  node.style.color = v.color || "var(--k-primary)";',
  '  var arrow = node.querySelector(".k-veh-arrow");',
  '  if (arrow) arrow.style.transform = "rotate(" + v.heading + "deg)";',
  '  var label = node.querySelector(".k-veh-label");',
  '  if (label) {',
  '    var late = v.delaySec > 30;',
  '    label.innerHTML = v.line + (late ? \' <em style="color:var(--k-error)">+\' + Math.round(v.delaySec / 60) + "</em>" : "");',
  '  }',
  '  if (following) {',
  '    map.easeTo({ center: [v.lon, v.lat], duration: 700 });',
  '  }',
  '}',
  '',
  'function setUser(u) {',
  '  if (!u) {',
  '    if (userMarker) { userMarker.remove(); userMarker = null; }',
  '    return;',
  '  }',
  '  if (!userMarker) {',
  '    var el = document.createElement("div");',
  '    el.className = "k-user";',
  '    el.innerHTML = \'<div class="k-user-halo"></div><div class="k-user-dot"></div>\';',
  '    userMarker = new maplibregl.Marker({ element: el });',
  '    userMarker.setLngLat([u.lon, u.lat]).addTo(map);',
  '  } else {',
  '    userMarker.setLngLat([u.lon, u.lat]);',
  '  }',
  '}',
  '',
  'function applyRoute(next) {',
  '  route = next;',
  '  legGeom = {};',
  '  for (var i = 0; i < route.legs.length; i++) {',
  '    var leg = route.legs[i];',
  '    var stops = leg.stops || [];',
  '    var pts = [];',
  '    for (var j = 0; j < stops.length; j++) pts.push([stops[j].lon, stops[j].lat]);',
  '    legGeom[leg.id] = pts;',
  '  }',
  '  if (selectedLeg && !legById(selectedLeg)) selectedLeg = null;',
  '  drawRoute();',
  '}',
  '',
  'function handle(msg) {',
  '  if (!msg || !msg.t) return;',
  '  if (msg.t === "route") {',
  '    applyRoute(msg.route);',
  '    if (msg.route) fitAll(null, false);',
  '    return;',
  '  }',
  '  if (msg.t === "geometry") {',
  '    if (!route || !msg.coords || msg.coords.length < 2) return;',
  '    legGeom[msg.legId] = msg.coords;',
  '    drawRoute();',
  '    return;',
  '  }',
  '  if (msg.t === "select") {',
  '    selectedLeg = msg.legId || null;',
  '    drawRoute();',
  '    setControlOffset(msg.pad);',
  '    if (selectedLeg) fitLeg(selectedLeg, msg.pad, true);',
  '    return;',
  '  }',
  '  if (msg.t === "fit") {',
  '    setControlOffset(msg.pad);',
  '    if (selectedLeg) fitLeg(selectedLeg, msg.pad, true);',
  '    else fitAll(msg.pad, true);',
  '    return;',
  '  }',
  '  if (msg.t === "vehicle") { setVehicle(msg.vehicle); return; }',
  '  if (msg.t === "follow") {',
  '    following = !!msg.on;',
  '    if (following) {',
  '      if (vehicleMarker) map.easeTo({ center: vehicleMarker.getLngLat(), duration: 600 });',
  '      else fitAll(null, true);',
  '    }',
  '    return;',
  '  }',
  '  if (msg.t === "user") { setUser(msg); return; }',
  '  if (msg.t === "center") {',
  '    map.easeTo({ center: [msg.lon, msg.lat], zoom: msg.zoom || Math.max(map.getZoom(), 16), duration: 600 });',
  '    return;',
  '  }',
  '}',
  '',
  // Pierwsza klatka potrafi przyjść, zanim kontener dostanie rozmiar — wtedy
  // fitBounds liczyłby zoom względem 0 px i trasa wylądowałaby poza ekranem.
  '  var fitTries = 0;',
  '  function fitWhenSized() {',
  '    var el = map.getContainer();',
  '    if ((!el.clientWidth || !el.clientHeight) && fitTries < 40) {',
  '      fitTries++;',
  '      map.once("render", fitWhenSized);',
  '      return;',
  '    }',
  '    if (BOOTSTRAP) fitAll(null, false);',
  '  }',
  '',
  'function bindLayerEvents() {',
  '  var stopLayer = P.stopLayerId;',
  '  if (map.getLayer(stopLayer)) {',
  '    map.on("click", stopLayer, function (e) {',
  '      var f = e.features && e.features[0];',
  '      if (!f) return;',
  '      var leg = legById(f.properties.legId);',
  '      var stop = leg ? (leg.stops || []).filter(function (s) { return s.id === f.properties.stopId; })[0] : null;',
  '      if (!stop) return;',
  '      post({ t: "stopTap", stopId: stop.id, legId: leg.id, name: stop.name, role: stop.role, arriveSec: stop.arriveSec });',
  '      showStopPopup(e.lngLat, stop, leg);',
  '    });',
  '  }',
  '  if (map.getLayer(P.hitLayerId)) {',
  '    map.on("click", P.hitLayerId, function (e) {',
  '      var f = e.features && e.features[0];',
  '      if (!f) return;',
  '      selectedLeg = f.properties.legId;',
  '      drawRoute();',
  '      post({ t: "legTap", legId: selectedLeg });',
  '    });',
  '  }',
  '  // Kursor wskaźnika nad trasą, inaczej mapa wygląda na martwą.',
  '  [P.hitLayerId, stopLayer].forEach(function (id) {',
  '    if (!map.getLayer(id)) return;',
  '    map.on("mouseenter", id, function () { map.getCanvas().style.cursor = "pointer"; });',
  '    map.on("mouseleave", id, function () { map.getCanvas().style.cursor = ""; });',
  '  });',
  '}',
  '',
  'function init() {',
  '  map = new maplibregl.Map({',
  '    container: "map",',
  '    style: P.style,',
  '    center: [17.0385, 51.1079],',
  '    zoom: 13,',
  '    minZoom: 9,',
  '    maxZoom: 19,',
  '    attributionControl: false,',
  '    fadeDuration: 120,',
  '    // Mapa pod rozkład jazdy nie ma się kręcić — obrót myli kierunek kursu.',
  '    dragRotate: false,',
  '    pitchWithRotate: false,',
  '    touchPitch: false,',
  '  });',
  '  map.dragRotate.disable();',
  '  map.touchZoomRotate.disableRotation();',
  '  map.keyboard.disable();',
  '  map.doubleClickZoom.disable();',
  '  attribution = new maplibregl.AttributionControl({ compact: false, customAttribution: P.attribution });',
  '  map.addControl(attribution, "bottom-right");',
  '  var attribEl = attribNode();',
  '  if (attribEl) attribEl.addEventListener("click", function (e) {',
  '    var a = e.target && e.target.closest ? e.target.closest("a") : null;',
  '    if (!a) return;',
  '    e.preventDefault();',
  '    post({ t: "open", url: a.href });',
  '  });',
  '  map.on("error", function (e) {',
  '    // Brak pojedynczej ikony/glyphu nie może wywrócić mapy — liczymy błędy',
  '    // i dopiero przy serii zgłaszamy problem sieci.',
  '    if (e && e.error && /Failed to fetch|NetworkError|Unauthorized|not found|404|403/.test(String(e.error.message || e.error))) {',
  '      loadFailures++;',
  '      if (loadFailures >= 6 && !tilesDown) { tilesDown = true; post({ t: "tiles", ok: false }); }',
  '    }',
  '  });',
  '  map.on("idle", function () {',
  '    if (tilesDown) { tilesDown = false; loadFailures = 0; post({ t: "tiles", ok: true }); }',
  '  });',
  '  map.on("movestart", function () {',
  '    if (vehicleMarker) vehicleMarker.getElement().classList.add("no-anim");',
  '  });',
  '  map.on("moveend", function () {',
  '    if (vehicleMarker) vehicleMarker.getElement().classList.remove("no-anim");',
  '  });',
  '  map.on("dragstart", function () {',
  '    if (following) { following = false; post({ t: "userMoved" }); }',
  '  });',
  '  // Trasa jest częścią stylu, więc wystarczy wczytanie stylu (kafelki mogą',
  '  // jeszcze dochodzić) — ekran pokazuje linię natychmiast, nie czekając na',
  '  // pierwszą klatkę mapy.',
  '  map.on("style.load", function () {',
  '    styleReady = true;',
  '    bindLayerEvents();',
  '    // Dopasowanie widoku: pierwsza klatka z gotowym rozmiarem kontenera.',
  '    map.once("render", function () {',
  '      map.resize();',
  '      fitWhenSized();',
  '    });',
  '    selectedLeg = P.selectedLegId || null;',
  '    if (BOOTSTRAP) applyRoute(BOOTSTRAP);',
  '    if (P.vehicle) setVehicle(P.vehicle);',
  '    if (P.user) setUser(P.user);',
  '    following = !!P.follow;',
  '    setControlOffset(null);',
  '    post({ t: "ready" });',
  '  });',
  '  // Bez WebGL albo bez sieci styl nie wczyta się wcale i widok zostaje',
  '  // czarny — mówimy wprost, zamiast udawać, że wszystko gra.',
  '  setTimeout(function () {',
  '    if (!styleReady) postError("Mapa nie wczytała się — brak sieci lub brak WebGL");',
  '  }, 20000);',
  '}',
  '',
  'window.addEventListener("message", function (event) {',
  '  var data = event.data;',
  '  if (!data) return;',
  '  try {',
  '    handle(typeof data === "string" ? JSON.parse(data) : data);',
  '  } catch (err) {',
  '    postError(err && err.message ? err.message : "zly komunikat");',
  '  }',
  '});',
  '',
  'loadMapLibre().then(init).catch(function (err) {',
  '  postError(err && err.message ? err.message : "mapa niedostepna");',
  '});',
  '})();',
].join('\n');

function bootstrapPayload(opts: RouteMapDocumentOptions): string {
  const payload = {
    cdns: MAPLIBRE_CDNS,
    style: buildMapStyle(),
    routeSourceId: ROUTE_SOURCE_ID,
    hitLayerId: 'trasa-chwyt',
    stopLayerId: 'przystanki-posrednie',
    attribution: MAP_ATTRIBUTION,
    padding: [42, 42, 190, 42],
    route: opts.route,
    vehicle: opts.vehicle ?? null,
    user: opts.user ?? null,
    follow: !!opts.follow,
    selectedLegId: opts.selectedLegId ?? null,
  };
  // Znak `<` w danych (nazwa przystanku) zamknąłby tag skryptu.
  return JSON.stringify(payload).replace(/</g, '\\u003c');
}

export function buildRouteMapDocument(opts: RouteMapDocumentOptions): string {
  return [
    '<!doctype html>',
    '<html lang="pl">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">',
    '<meta name="color-scheme" content="dark">',
    '<title>Mapa trasy</title>',
    '<style>' + css + '</style>',
    '</head>',
    '<body>',
    '<div id="map"></div>',
    '<script>window.__KM__ = ' + bootstrapPayload(opts) + ';</script>',
    '<script>' + runtime + '</script>',
    '</body>',
    '</html>',
  ].join('\n');
}

export type { MapInMessage, MapOutMessage, MapRoute, MapVehicle };
